# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
version: "3"
services:
    execution:
        image: ethereum/client-go:v1.17.4
        container_name: execution
        restart: always
        command:
            [
                "--${BC_NETWORK}",
                "--metrics",
                "--pprof",
                "--authrpc.addr=0.0.0.0",
                "--authrpc.jwtsecret=/var/lib/geth/secrets/jwtsecret",
                "--authrpc.vhosts=*",
                "--http.vhosts=*",
                "--http",
                "--http.api=admin,eth,web3,txpool,net,debug,engine",
                "--http.addr=${EC2_INTERNAL_IP}",
                "--ws",
                "--ws.addr=${EC2_INTERNAL_IP}",
                "--db.engine=pebble",
                "--datadir=/var/lib/geth/data",
                "--maxpeers=50",
                "--cache=16000",
            ]
        volumes:
            - /secrets:/var/lib/geth/secrets
            - /data/execution:/var/lib/geth/data
        stop_signal: SIGTERM
        stop_grace_period: 8m
        security_opt:
            - no-new-privileges:true
        read_only: true
        network_mode: host

    consensus:
        image: sigp/lighthouse:v8.2.1
        container_name: consensus
        restart: always
        command:
            [
                "lighthouse",
                "beacon",
                "--network=${BC_NETWORK}",
                "--execution-endpoint=http://127.0.0.1:8551",
                "--execution-jwt=/var/lib/lighthouse/secrets/jwtsecret",
                "--checkpoint-sync-url=${ETH_CONSENSUS_CHECKPOINT_SYNC_URL}",
                "--http",
                "--http-port=5052",
                "--http-address=${EC2_INTERNAL_IP}",
                "--metrics",
                "--metrics-address=${EC2_INTERNAL_IP}",
                "--datadir=/var/lib/lighthouse/data",
                "${ETH_CONSENSUS_SUPERNODE_FLAG}",
            ]
        depends_on:
            - execution
        volumes:
            - /secrets:/var/lib/lighthouse/secrets
            - /data/consensus:/var/lib/lighthouse/data
        stop_signal: SIGTERM
        stop_grace_period: 5m
        security_opt:
            - no-new-privileges:true
        read_only: true
        network_mode: host
