# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
version: "3"
services:
    execution:
        image: nethermind/nethermind:1.39.0
        container_name: execution
        restart: always
        command:
            [
                "--config=${BC_NETWORK}",
                "--JsonRpc.Enabled=true",
                "--JsonRpc.Host=${EC2_INTERNAL_IP}",
                "--JsonRpc.JwtSecretFile=/var/lib/nethermind/secrets/jwtsecret",
                "--JsonRpc.EngineHost=0.0.0.0",
                "--JsonRpc.EnginePort=8551",
                "--datadir=/var/lib/nethermind/data",
                "--Network.MaxActivePeers=50",
            ]
        volumes:
            - /secrets:/var/lib/nethermind/secrets
            - /data/execution:/var/lib/nethermind/data
        stop_signal: SIGTERM
        stop_grace_period: 8m
        security_opt:
            - no-new-privileges:true
        network_mode: host

    consensus:
        image: consensys/teku:26.7.0
        container_name: consensus
        restart: always
        command:
            [
                "--network=${BC_NETWORK}",
                "--ee-endpoint=http://127.0.0.1:8551",
                "--ee-jwt-secret-file=/var/lib/teku/secrets/jwtsecret",
                "--checkpoint-sync-url=${ETH_CONSENSUS_CHECKPOINT_SYNC_URL}",
                "--rest-api-enabled=true",
                "--rest-api-port=5052",
                "--rest-api-interface=${EC2_INTERNAL_IP}",
                "--rest-api-host-allowlist=*",
                "--metrics-enabled=true",
                "--metrics-interface=${EC2_INTERNAL_IP}",
                "--data-path=/var/lib/teku/data",
            ]
        depends_on:
            - execution
        volumes:
            - /secrets:/var/lib/teku/secrets
            - /data/consensus:/var/lib/teku/data
        stop_signal: SIGTERM
        stop_grace_period: 5m
        security_opt:
            - no-new-privileges:true
        network_mode: host
