// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Environment configuration generated by stacks during deployment 
 * and used in user data script to access asset resources (shell scripts) 
 * and send signals to CloudFormation service
 */
export interface CFNandCDKUserDataConfig {
    STACK_NAME: string,
    LOGICAL_RESOURCE_ID: string,
    ASG_NAME: string,
    LIFECYCLE_HOOK_NAME: string,
    COMMON_ASSETS_S3_PATH: string,
    PROTOCOL_ASSETS_S3_PATH: string,
    SNAPSHOT_STAGING_VOL_ID: string,
}
