#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Solana Frankendancer - Extended RPC Node Configuration
# Provides full RPC API access including account indexing for advanced queries
# Generates TOML configuration and runs fdctl with system initialization
# Suitable for dApps requiring token owner/program/mint index lookups
#
# Reference: https://docs.firedancer.io/guide/configuring.html
# Reference: https://docs.firedancer.io/guide/initializing.html

set -o errexit
set -o nounset
set -o pipefail

# Remove empty snapshots to avoid startup issues
find "/data/data/ledger" -name "snapshot-*" -size 0 -print -exec rm {} \; 2>/dev/null || true

# Get EC2 internal IP for RPC binding
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
EC2_INTERNAL_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/local-ipv4)

echo "Starting Frankendancer validator (extended RPC) on $EC2_INTERNAL_IP..."
echo "Network: ${BC_NETWORK:-mainnet-beta}"

# Set network-specific parameters
case "${BC_NETWORK:-mainnet-beta}" in
    "mainnet-beta")
        GOSSIP_ENTRYPOINTS='    entrypoints = [
        "entrypoint.mainnet-beta.solana.com:8001",
        "entrypoint2.mainnet-beta.solana.com:8001",
        "entrypoint3.mainnet-beta.solana.com:8001",
        "entrypoint4.mainnet-beta.solana.com:8001",
        "entrypoint5.mainnet-beta.solana.com:8001",
    ]'
        EXPECTED_GENESIS_HASH="5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d"
        KNOWN_VALIDATORS='    known_validators = [
        "7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2",
        "GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ",
        "DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ",
        "CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S",
    ]'
        SOLANA_METRICS="host=https://metrics.solana.com:8086,db=mainnet-beta,u=mainnet-beta_write,p=password"
        ;;
    "testnet")
        GOSSIP_ENTRYPOINTS='    entrypoints = [
        "entrypoint.testnet.solana.com:8001",
        "entrypoint2.testnet.solana.com:8001",
        "entrypoint3.testnet.solana.com:8001",
    ]'
        EXPECTED_GENESIS_HASH="4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY"
        KNOWN_VALIDATORS='    known_validators = [
        "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
        "dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs",
        "Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN",
        "eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ",
        "9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv",
    ]'
        SOLANA_METRICS="host=https://metrics.solana.com:8086,db=tds,u=testnet_write,p=c4fa841aa918bf8274e3e2a44d77568d9861b3ea"
        ;;
    "devnet")
        GOSSIP_ENTRYPOINTS='    entrypoints = [
        "entrypoint.devnet.solana.com:8001",
        "entrypoint2.devnet.solana.com:8001",
        "entrypoint3.devnet.solana.com:8001",
        "entrypoint4.devnet.solana.com:8001",
        "entrypoint5.devnet.solana.com:8001",
    ]'
        EXPECTED_GENESIS_HASH="EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG"
        KNOWN_VALIDATORS='    known_validators = [
        "dv1ZAGvdsz5hHLwWXsVnM94hWf1pjbKVau1QVkaMJ92",
        "dv2eQHeP4RFrJZ6UeiZWoc3XTtmtZCUKxxCApCDcRNV",
        "dv4ACNkpYPcE3aKmYDqZm9G5EB3J4MRoeE7WNDRBVJB",
        "dv3qDFk1DTF36Z62bNvrCXe9sKATA6xvVy6A798xxAS",
    ]'
        SOLANA_METRICS="host=https://metrics.solana.com:8086,db=devnet,u=scratch_writer,p=topsecret"
        ;;
    *)
        echo "ERROR: Unknown BC_NETWORK: ${BC_NETWORK}. Supported: mainnet-beta, testnet, devnet"
        exit 1
        ;;
esac

# Generate TOML configuration file
CONFIG_DIR="/home/bcuser/config"
CONFIG_FILE="${CONFIG_DIR}/frankendancer.toml"
mkdir -p "$CONFIG_DIR"

echo "Generating Frankendancer TOML configuration at $CONFIG_FILE..."

cat > "$CONFIG_FILE" <<TOML_EOF
# Frankendancer - Extended RPC Configuration
# Generated by AWS Blockchain Node Runners
# Network: ${BC_NETWORK:-mainnet-beta}

user = "bcuser"

dynamic_port_range = "8004-8029"

[log]
    path = "-"
    level_logfile = "INFO"
    level_stderr = "NOTICE"
    level_flush = "WARNING"

[reporting]
    solana_metrics_config = "${SOLANA_METRICS}"

[gossip]
${GOSSIP_ENTRYPOINTS}
    port = 8001

[consensus]
    identity_path = "/home/bcuser/config/validator-keypair.json"
    expected_genesis_hash = "${EXPECTED_GENESIS_HASH}"
${KNOWN_VALIDATORS}

[rpc]
    port = 8899
    bind_address = "${EC2_INTERNAL_IP}"
    full_api = true
    transaction_history = true
    extended_tx_metadata_storage = true
    private = true

[ledger]
    path = "/data/data/ledger"
    accounts_path = "/accounts"
    limit_size = 200000000
    account_indexes = [
        "spl-token-owner",
        "program-id",
        "spl-token-mint",
    ]
    account_index_exclude_keys = [
        "kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6",
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
    ]

[layout]
    affinity = "auto"
    agave_affinity = "auto"

[hugetlbfs]
    mount_path = "/mnt/.fd"

[tiles.shred]
    shred_listen_port = 8003
TOML_EOF

chown bcuser:bcuser "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"
echo "TOML configuration generated successfully"

# Perform system initialization (hugetlbfs, sysctl, ethtool)
# This must run as root before starting the validator
echo "Running fdctl configure init all (system initialization)..."
/home/bcuser/bin/fdctl configure init all --config "$CONFIG_FILE"
echo "System initialization completed successfully"

# Create init-completed sentinel file once RPC becomes responsive.
# fdctl does not support --init-complete-file (an Agave-only flag).
# syncchecker.sh gates all metric reporting and traffic shaping behind
# this file, so without it those features never activate.
/opt/blueprints/user-data/common/wait-for-rpc.sh &

# Start the validator
# fdctl must run as root for AF_XDP networking; it drops privileges to bcuser internally
echo "Starting Frankendancer validator..."
exec /home/bcuser/bin/fdctl run --config "$CONFIG_FILE"
