/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Blueprints',
      items: [{ type: 'autogenerated', dirName: 'blueprints' }],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'AI Workflow Reference',
      items: [{ type: 'autogenerated', dirName: 'ai-prompts' }],
    },
  ],
};

module.exports = sidebars;
