name: blueprints-cdk-tests

on:
  pull_request:
    branches:
      - main

jobs:
  blueprints-cdk-tests:
    name: Run CDK tests for all blueprints
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: ./run-all-cdk-tests.sh
